sudo: required
services:
  - docker

before_install:
  - docker build -t okradze/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true okradze/docker-react npm run test -- --coverage

language: generic